author:
  name: Daniel Engbert
  resumeurl: /resume.pdf
  email: end1@umbc.edu
  github: dangbert
  linkedin: danielengbert
  #twitter: <username>
baseURL: https://www.engbert.me/
#disqusShortname: dannyguo
enableRobotsTXT: true
#googleAnalytics: UA-90320718-1
languageCode: en-us
pygmentsCodefences: true
pygmentsStyle: monokai
rssLimit: 20
title: Daniel Engbert

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  RSS:
    mediatype: application/rss
    baseName: feed

outputs:
  home:
    - HTML
    - Algolia

params:
  # TODO:
  sourceCodeRepo: https://github.com/dguo/dguo.github.io/blob/master
