[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.53"

[context.production.environment]
  HUGO_ENV = "production"

#[[redirects]]
#  from = "/blood-moon"
#  to = "https://www.blood-moon.dannyguo.com"
#  status = 301
